### ISSUE TITLE
In case of authentication with Private Key, the default username is not set to git.

### ISSUE THREAD

**Issue by rampreeth** [KohlsTechnology/git2consul-go#13]
(While submitting an issue briefly describe the problem you are facing or a new feature you would want to see added) 

## What happens?
When I don't specify pk_username in my config.json file, I would expect it to be set to git by default as per the documentation. What happens is that when I run the git2consul binary , I got the following error:
 ERROR[0001] (runner): Cannot load repositories from configuration: Error loading <repo-name>: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
...

## What were you expecting to happen?
I would expect the username to be set to git by default.
...

## Steps to reproduce: 

* ...
* ...

## Any errors, stacktrace, logs? 

...

## Environment:

* Runtime version(Java, Go, Python, etc):
* Desktop OS/version:

## Additional comments:

...

**Comment by rampreeth** [comment]
Right now, there is a check being done for repo.Credentials.Username, just needs to be changed to repo.Credentials.PrivateKey.Username in repository/auth.go. Can I pick this up?

**Comment by seanmalloy** [comment]
@rampreeth thanks for open this issue! Yes, you can submit a fix for this issue that would be great.

**Comment by rampreeth** [comment]
@seanmalloy Thanks!

**Comment by rampreeth** [comment]
@seanmalloy can you please take a look at this

**Comment by seanmalloy** [comment]
@rampreeth I've added this to the v0.1.2 milestone which will be the next release. Hopefully by the end of February.

**Comment by seanmalloy** [comment]
Closed by #14
