### ISSUE TITLE
End User Docs Difficult to Follow

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/git2consul-go#29]
**What version of git2consul-go are you using?**

<pre>
$ git2consul -version
git2consul, version v0.1.1 (branch: HEAD, revision: abdf3a1d746539f08ce5122f9d7db43ae4e79afd)
build date: 20200106-19:50:06
go version: go1.13.5
</pre>

**Does this issue reproduce with the latest release?**

Yes.

**What operating system and processor architecture are you using (`uname  -a`)?**

<details><summary><code>uname -a</code> Output</summary><br><pre>
$ uname -a
Darwin 17.7.0 Darwin Kernel Version 17.7.0: Sun Dec  1 19:19:56 PST 2019; root:xnu-4570.71.63~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,4 Darwin
</pre></details>

**What did you do?**

I read the README.md file.

**What did you expect to see?**

An easy to follow user guide with examples that show how to get started with and use git2consul.

**What did you see instead?**

My opinion is that the README.md files is not easy to follow. I think it needs to be re-written.

**Comment by bbaassssiiee** [comment]
A larger example would be GREAT!
