### ISSUE TITLE
Add better support for yaml lists

### ISSUE THREAD

**Issue by Garagoth** [KohlsTechnology/git2consul-go#37]
**Is your feature request related to a problem? Please describe.**
Yes. I am trying to load yaml files that contain lists of strings.
git2consul supports only lists of maps and crashes in my case.

**Describe the solution you'd like**
You already create keys that are list indices, but assume that value of list is a map.
Please create keys that as value have strings.

**Describe alternatives you've considered**
Having this yaml:
```
---
main:
  name: test
  tags:
    - lab
    - feature-x
```
I can only consider mutating this into:
```
---
main:
  name: test
  tags:
    0: lab
    1: feature-x
```
While consul KV contents will be the same, yaml representation is a bit awkward.

**What version of git2consul-go are you using?**
Latest, cloned from this repo.
<pre>
$ git2consul -version
0.1.2-dev
</pre>

**Additional content**
The crash is here: https://github.com/KohlsTechnology/git2consul-go/blob/9f404c06fe43479f3d81f237cee0ae93b3964905/kv/filehandler.go#L169
```
panic: interface conversion: interface {} is string, not map[interface {}]interface {}
goroutine 20 [running]:
github.com/KohlsTechnology/git2consul-go/kv.entriesToKV(0xc00044f3b0, 0xc00044f380)
	/home/dzareba/g2c/git2consul-go/kv/filehandler.go:169 +0xa75
github.com/KohlsTechnology/git2consul-go/kv.entriesToKV(0xc00044f380, 0xc00044f350)
	/home/dzareba/g2c/git2consul-go/kv/filehandler.go:164 +0x634
github.com/KohlsTechnology/git2consul-go/kv.entriesToKV(0xc00044f350, 0xc00044f290)
	/home/dzareba/g2c/git2consul-go/kv/filehandler.go:164 +0x634
github.com/KohlsTechnology/git2consul-go/kv.entriesToKV(0xc00044f290, 0xc0004353fc)
	/home/dzareba/g2c/git2consul-go/kv/filehandler.go:164 +0x634
github.com/KohlsTechnology/git2consul-go/kv.(*YAMLFile).Create(0xc000445910, 0x9d5360, 0xc000130db0, 0x9da6c0, 0xc000130ae0, 0xc000445910, 0xffffffffffffff9c)
	/home/dzareba/g2c/git2consul-go/kv/filehandler.go:119 +0x1c2
github.com/KohlsTechnology/git2consul-go/kv.(*KVHandler).putBranch.func1(0xc0004353c0, 0x40, 0x9d7a40, 0xc000155d40, 0x0, 0x0, 0x4c2d99, 0xc000155d40)
	/home/dzareba/g2c/git2consul-go/kv/branch.go:56 +0x10b
path/filepath.walk(0xc0004353c0, 0x40, 0x9d7a40, 0xc000155d40, 0xc0000fdca8, 0x0, 0x0)
	/home/dzareba/go/src/path/filepath/path.go:358 +0x425
```

**Comment by seanmalloy** [comment]
@Garagoth thanks opening this issue. Would you be willing to submit a pull request for this enhancement request?

**Comment by stevenscg** [comment]
@Garagoth Have you encountered this error under other conditions?

We have a large config repo that does not have yaml lists as far as we know. We get the same error and have not yet been able to locate which file(s) could have an issue.

FWIW, we are trying to migrate from the breser/git2consul project and all of the files are yaml.

**Comment by Garagoth** [comment]
@seanmalloy I am not fluent in go, so my pull request would be of poor quality I am afraid. I would need to learn a bit for this.

@stevenscg so far only with arrays of things that are not maps. Check for constructs like this as well:
`key: [v1, v2, v3] `
This is a valid array in yaml as well.

**Comment by stevenscg** [comment]
@Garagoth Thanks. I'll try to look into it more later.

@seanmalloy Do you happen to know if there is a way to see _which_ file is causing a problem when we see this error message? Maybe by increasing the log level?

**Comment by stevenscg** [comment]
@Garagoth Thanks for that pattern! We found that we have 1 line like that in 1 file in each tree. I'll try removing it for now as a workaround.

**Comment by replicant0wnz** [comment]
Any update on this? I'm seeing the same behaviour.

**Comment by Smiley73** [comment]
@replicant0wnz unfortunately we're very short staffed and won't get to it any time soon. A pull request for this would be greatly appreciated. :)

**Comment by replicant0wnz** [comment]
So, I'm kinda an idiot. Consul doesn't support lists, it's key/value. It supports lists in the manner that the value can be raw json or yaml. So if you want a list you have to store it as such. So just do:

```
test: |
- blah
- blah
- blah
```
If the code was modified, it would have to store it that way anyway .. May be kinda a pain if you already have existing yaml code, but we are starting from scratch so we're just gonna use this method.

**Comment by replicant0wnz** [comment]
Well, it'll still crash if it receives a list. I'd say better sanity checking at a minimum. I may be able to tackle it later, but my golang knowledge is minimal.
