### ISSUE TITLE
Wrong default value for polling interval

### ISSUE THREAD

**Issue by leoblanc** [KohlsTechnology/git2consul-go#42]
**What version of git2consul-go are you using?**

<pre>
$ git2consul -version
git2consul, version v0.1.1 (branch: HEAD, revision: abdf3a1d746539f08ce5122f9d7db43ae4e79afd)
build date: 20200106-19:50:06
go version: go1.13.5
</pre>

**Does this issue reproduce with the latest release?**

Yes, at least this is the latest release

**What operating system and processor architecture are you using (`uname  -a`)?**

<details><summary><code>uname -a</code> Output</summary><br><pre>
$ uname -a
Linux xxxxxxx 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
</pre></details>

**What did you do?**
git2consul -config ./config.json -debug

**What did you expect to see?**

I expected to see that my new commits are updated every 60 seconds because the README file says that the default value for repos:hooks:interval is 60.

**What did you see instead?**

After 60 seconds (or even several minutes) nothing is updated. It seems like the default value is not 60, it's 60000000000 according to the logs:

```
  INFO[0000] Starting git2consul version: v0.1.1
  INFO[0000] Setting configuration with sane defaults caller=config
 DEBUG[0000] Using configuration: {"local_store":"/tmp/git2consul","webhook":{"port":9000},"repos":[{"name":"consul-base-development","url":"ssh://10.1.1.11/obfuscated/consul.git","branches":["master"],"hooks":[{"type":"polling","interval":60000000000}],"source_root [...]
```

**Comment by seanmalloy** [comment]
@leoblanc thanks for creating this bug report!

Here more some notes regarding this bug ...
* Here is the code that sets the [default polling interval](https://github.com/KohlsTechnology/git2consul-go/blob/e3a77c6281164522299992577621364ae7045c19/config/load.go#L140-L145)
* Here is the [debug log statement](https://github.com/KohlsTechnology/git2consul-go/blob/e3a77c6281164522299992577621364ae7045c19/config/load.go#L66) that produces the `Using configuration:` log message
* Here is where the polling interval is [stored in a struct](https://github.com/KohlsTechnology/git2consul-go/blob/16370b1faea57e61d5a90b079206a3c7dbbe2065/config/config.go#L40)

**Comment by ttys3** [comment]
@dingweiqings  I fixed it like this: https://github.com/ttys3/git2consul-go/commit/2ba226bb7f7b814f648a422d96d393fabff00b45
