### ISSUE TITLE
Add support for configurable "repos:expand_keys" file extension

### ISSUE THREAD

**Issue by MartijnDekkers** [KohlsTechnology/git2consul-go#45]
**Is your feature request related to a problem? Please describe.**

I would like to have the ability to expand keys in a YAML file, but I also want to import some .yml files as blobs

**Describe the solution you'd like**

I would like to have the ability to define a custom file extension to treat as expandable YAML

**Describe alternatives you've considered**

I have made a small patch that will add this functionality:
<pre>
config/config.go:
  MountPoint     string      `json:"mount_point"`
  ExpandKeys     bool        `json:"expand_keys,omitempty"`
  ExpandExt      string      `json:"expand_ext,omitempty"`
  SkipBranchName bool        `json:"skip_branch_name,omitempty"`

kv/filehandler.go:
func Init(path string, repo repository.Repo) File {
  config := repo.GetConfig()
  expandKeys := config.ExpandKeys
  expandExt := config.ExpandExt
  var f File
  ext := filepath.Ext(path)
  if expandKeys {
    if ext == expandExt {
      f = &YAMLFile{path: path}
    }
  }
</pre>

 Unfortunately I don't really know golang, and I don't really know how to reliably default to ".yml" if no extension was specified.

**What version of git2consul-go are you using?**
<pre>
$ git2consul -version
git2consul, version v0.1.1 (branch: HEAD, revision: abdf3a1d746539f08ce5122f9d7db43ae4e79afd)
build date: 20200106-19:50:06
go version: go1.13.5
</pre>

**Additional context**

**Comment by Smiley73** [comment]
@MartijnDekkers would it make more sense to provide a command line parameter that enables this features?

**Comment by MartijnDekkers** [comment]
@Smiley73 yeah, that would work as well. I will see if I can cobble something together
