### ISSUE TITLE
git2consul destroys kv store

### ISSUE THREAD

**Issue by MartijnDekkers** [KohlsTechnology/git2consul-go#46]
**What version of git2consul-go are you using?**

<pre>
$ git2consul -version
git2consul, version v0.1.1 (branch: HEAD, revision: abdf3a1d746539f08ce5122f9d7db43ae4e79afd)
build date: 20200106-19:50:06
go version: go1.13.5
</pre>

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`uname  -a`)?**

<details><summary><code>uname -a</code> Output</summary><br><pre>
$ uname -a
Linux mainws 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
</pre></details>

**What did you do?**
I was working to get the "refs" key generated by git2consul and the actual data from git under the same key. The documentation is quite sparse, so this is a trial an error process. One of the setups of config.json resulted in a nameless top-level key being created in Consul that was not readable. Deleting this key completely wiped the Consul KV store.

for a git repo structured like so:
`<root>/services/testservice/<data>`
with a config structured like so:
```
{
  "repos": [
    {
      "name": "/playground/tenant/services/testservice/",
      "url": "ssh://git@git.service/playground.git",
      "source_root": "/services/testservice/",
      "expand_keys": true,
      "mount_point": "playground/tenant/",
      "skip_branch_name": true
    }
  ]
}
```
The result is a key with no name as the top level key in the Consul KV store. Removing this key using the Consul GUI results in the complete K/V store being wiped.

**What did you expect to see?**
Anything but this...

**What did you see instead?**
A key with no name as the top level key in the Consul KV store

**Comment by Smiley73** [comment]
@MartijnDekkers thanks for submitting the issue. It would be great if you could send in a pull request. We're unfortunately short on people right now, due to the pandemic...

**Comment by donndonn** [comment]
I think this is an issue with consul itself. 
When I used the http api to create a key with leading '/', the UI breaks as well. But you can still query/delete it with http api, just the UI is broken.
```
curl -X PUT \
  https: //demo.consul.io/v1/txn \
  -d '[
  {
    "KV": {
      "Verb": "set",
      "Key": "/txntesting/1",
      "Value": "dHhudGVzdGluZw=="
    }
  }
]
```

```
curl http://demo.consul.io/v1/kv/\?recurse=true

[{"LockIndex":0,"Key":"/txntesting/1","Flags":0,"Value":"dHhudGVzdGluZw==","CreateIndex":24936,"ModifyIndex":24936}]
```
