### ISSUE TITLE
Question: Connecting to Azure Devops git repos

### ISSUE THREAD

**Issue by Cirzen** [KohlsTechnology/git2consul-go#53]
Has anyone managed to get Git2Consul working with Azure Devops repos? I have tried all kinds of authentication approaches, but am having no luck. Just getting ` ERROR[0001] Runner error              error=reference not found` every time, which I'm having trouble deciphering.
If anyone has got this working, any advice would be welcome, especially with some example config.
I'll report back if I get it working in the interim.

**Comment by jmgilman** [comment]
Can confirm it simply doesn't work - even when no authentication is required. Don't have the capacity to investigate it further, but in my case it was complaining it needed authentication details when trying to clone a public repository.
