### ISSUE TITLE
Add link to consul.io

### ISSUE THREAD

**Issue by Smiley73** [KohlsTechnology/git2consul-go#8]
## What happens?
We should add a link to git2consul.go on the website: https://www.consul.io/downloads_tools.html
All it needs is a PR: https://github.com/hashicorp/consul

## What were you expecting to happen?
Everybody can find out tool.

## Steps to reproduce: 
N/A

## Any errors, stacktrace, logs? 
N/A

## Environment:
N/A

## Additional comments:
N/A

**Comment by bjaroszewski** [comment]
PR created: https://github.com/hashicorp/consul/pull/6286

**Comment by bjaroszewski** [comment]
PR merged - issue can be closed
